name: workflow dispatch

on:
 workflow_dispatch: 

 jobs:
 print-message:
 runs-on: ubuntu-latest
   steps:
   - name: First Step
   run: echo "Starting the workflow!"

   - name: Second Step
   run: echo "Processing Data...."

   -name: Third Step
   run: echo "Processing completed"
 
    
