name: workflow_dispatch

on: workflow_dispatch

env:
  My_Name: John Cena
  My_Env: Learning

jobs:
  Print-message:
    runs-on: ubuntu-latest

    env:
      Job_Name: Terraform Job

    steps:
      - name: First Step
        run: echo "Starting the workflow"

      - name: Second Step
        run: echo "Processing data"

      - name: Third Step
        run: echo "Processing completed"

      - name: Fourth Step
        env:
          STEP_VAR: "Step_Level_Var"
        run: echo "Step variable is $STEP_VAR"

      - name: Fifth Step
        env:
           SECRET_NAME: ${{ secrets.MY_SECRET_NAME }}
        run: echo "My name from secret is $SECRET_NAME"

      - name: Sixth step
        env:
           SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: echo "Token is $SECRET_TOKEN"

      - name: Seventh Step
        run: echo "${{ secrets.MY_SECRET_NAME }}"
        
